apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-worker
  template:
    metadata:
      labels:
        app: document-worker
    spec:
      containers:
        - name: worker
          image: document-worker:latest
